# Generated by Django 2.0.7 on 2018-07-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20180721_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'track', 'verbose_name_plural': 'tracks'},
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
        migrations.AlterModelTable(
            name='track',
            table='track',
        ),
    ]
