# Generated by Django 2.0.7 on 2018-07-22 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0003_auto_20180722_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedTopics',
            new_name='CompletedTopic',
        ),
        migrations.AlterModelOptions(
            name='completedtopic',
            options={'verbose_name': 'completed topic', 'verbose_name_plural': 'completed topics'},
        ),
        migrations.AlterModelTable(
            name='completedtopic',
            table='completed_topic',
        ),
    ]
