# Generated by Django 2.0.7 on 2018-07-24 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20180723_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Topic'),
        ),
        migrations.AlterField(
            model_name='completedtopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.Track'),
        ),
    ]
