# Generated by Django 2.0.7 on 2018-07-17 14:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar-image.png', upload_to=accounts.models.user_directory_path, verbose_name='Profile Picture'),
        ),
    ]
