# Generated by Django 2.0.7 on 2018-07-31 12:38

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=resources.models.document_directory_path),
        ),
    ]
