# Generated by Django 2.0.7 on 2018-07-11 12:59

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=100)),
                ('salt', models.CharField(blank=True, default=authentication.models.get_salt, max_length=32)),
                ('time_stamp', models.CharField(blank=True, default=authentication.models.get_timestamp, max_length=32)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'account verification',
                'verbose_name_plural': 'accounts verification',
            },
        ),
    ]
